<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Magenerds
 * @package    Magenerds_BasePrice
 * @subpackage view
 * @author     Florian Sydekum <f.sydekum@techdivision.com>
 * @copyright  Copyright (c) 2017 TechDivision GmbH (http://www.techdivision.com)
 * @link       http://www.techdivision.com/
 */

/**
 * @var $block \Magenerds\BasePrice\Block\AfterPrice
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="baseprice">
        <?php echo $block->getBasePrice() ?>
    </div>
<?php endif; ?>