<?php
/**
 * Copyright (c) 2016 TechDivision GmbH
 * All rights reserved
 *
 * This product includes proprietary software developed at TechDivision GmbH, Germany
 * For more information see http://www.techdivision.com/
 *
 * To obtain a valid license for using this software please contact us at
 * license@techdivision.com
 */

/**
 * @category   Magenerds
 * @package    Magenerds_BasePrice
 * @subpackage view
 * @author     Florian Sydekum <f.sydekum@techdivision.com>
 * @copyright  Copyright (c) 2016 TechDivision GmbH (http://www.techdivision.com)
 * @version    ${release.version}
 * @link       http://www.techdivision.com/
 */

/**
 * @var $block \Magenerds\BasePrice\Block\AfterPrice
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="baseprice">
        <?php echo $block->getBasePrice() ?>
    </div>
<?php endif; ?>